setwd("Desktop/work/final")
library(dplyr)
asvtab <- read.table('ASVs_counts.tsv', header=TRUE, row.names=1, check.names=FALSE, sep="\t")
asv_tax<-read.table('ASVs_taxonomy.tsv',header=TRUE, row.names=1, check.names=FALSE, sep="\t",na.strings="NA")
sample_info_tab <- read.table("metadata_p.tsv",header=TRUE, row.names=1, check.names=FALSE, sep="\t")
asvtab_1 <- asvtab/apply(asvtab,2,sum)
old<- as.character(rownames(filter(sample_info_tab, Old=="Yes")))
new<-as.character(rownames(filter(sample_info_tab, Old=="No")))
ms <-as.character(rownames(filter(sample_info_tab, Sampling=="ms")))
r<- as.character(rownames(filter(sample_info_tab, Sampling=="r")))

tax_rothia<- rownames(filter(asv_tax, genus=="Rothia"))
tax_strepto<- rownames(filter(asv_tax, genus=="Streptococcus"))
tax_gemela <- rownames(filter(asv_tax, genus=="Gemella"))
tax_haem <- rownames(filter(asv_tax, genus=="Haemophilus"))
tax_allo <- rownames(filter(asv_tax, genus=="Alloiococcus"))
tax_actinobacter<- rownames(filter(asv_tax, genus=="Acinetobacter"))
tax_cultibacterium<- rownames(filter(asv_tax, genus=="Cutibacterium"))
tax_steno<- rownames(filter(asv_tax, genus=="Stenotrophomonas"))
tax_corynebacterium<- rownames(filter(asv_tax, genus=="Corynebacterium"))
tax_staph<- rownames(filter(asv_tax, genus=="Staphylococcus"))
colnames(asvtab_1)<-as.character(colnames(asvtab_1))

gemella_ms <- as.vector(t(asvtab_1[tax_rothia[1:length(tax_rothia)],ms[1:length(ms)]]))
gemella_r <-as.vector(t(asvtab_1[tax_rothia[1:length(tax_rothia)],r[1:length(r)]]))
t.test(gemella_ms,gemella_r)
