library("knitr")
library("BiocStyle")
#install.packages("umap")
library(ggplot2)
library(dada2)
packageVersion("dada2") 
library(DECIPHER)
library(readr)
library(phangorn)
library(DiagrammeR)
library(DiagrammeRsvg)
library(Rgraphviz)
library(phyloseq)
library(DESeq2)
library(dendextend)
library(vegan)
library(extrafont)
library(dplyr)
library(tidyr)
library(umap)
library("animalcules")
setwd("Desktop/")

asvtab <- read.table('../ASVs_counts.tsv', header=TRUE, row.names=1, check.names=FALSE, sep="\t")
asv_tax<-read.table('../ASVs_taxonomy.tsv',header=TRUE, row.names=1, check.names=FALSE, sep="\t",na.strings="NA")
sample_info_tab <- read.table("../metadata_p.tsv",header=TRUE, row.names=1, check.names=FALSE, sep="\t")
run_animalcules()
asv_tax_new<- as.matrix(asv_tax_new)
# and setting the color column to be of type "character", which helps later

#########################################################TAXONOMY########################################################################
###########################phylum################################################
vst_physeq <- phyloseq(otu_table(asvtab, taxa_are_rows=T), sample_names(sample_info_tab), tax_table(asv_tax))

asvtab_new<-read.table('ASVs_counts_new.tsv', header=TRUE, row.names=1, check.names=FALSE, sep="\t")
asv_tax_new<-read.table('ASVs_taxonomy_new.tsv',header=TRUE, row.names=1, check.names=FALSE, sep="\t")
vst_physeq_new <-phyloseq(otu_table(asvtab_new, taxa_are_rows=T), sample_data(sample_info_tab), taxa,treeNJ_rooted)
phylo_1 <- prune_samples(sample_sums(vst_physeq_new) > 10000, vst_physeq_new)
rarecurve(t(otu_table(phylo_1)), step=50, cex=0.5, label = )
rarecurve(t(otu_table(phylo_1)), step=50,  lwd=4, ylab='ASVs', label=F,cex.main=4,cex.names=4, cex =1, cex.lab=3,cex.axis=2.5)

wunifrac_dist = phyloseq::distance(phylo_1, method="wunifrac")
ordination = ordinate(phylo_1, method="PCoA", distance=wunifrac_dist)
png("Type_of_birthgiving.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Type_of_birthgiving") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Экстренное кесарево (ЭКС)", "Кесарево сечение (КС)", "Естественные роды (ЕР)"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+labs(fill = "Тип родоразрешения")
dev.off()
png("nab.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "nab") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+labs(fill = "Прием антибиотиков во время беременности")
dev.off()
png("Ab_days_after_birth.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Ab_days_after_birth") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Прием антибиотиков после родов")
dev.off()
png("Breast_treatment.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Breast_treatment") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Фурацилин", "Хлоргексидин", "Мыло"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Прием антибиотиков после родов")
dev.off()
png("Stationary_time.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Stationary_time") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Длительное", "Короткое"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Время пребывания в стационаре")
dev.off()
png("Old.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Old") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Молозиво", "Зрелое молоко"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Степень зрелости молока")
dev.off()
png("Sampling.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Sampling") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Молокоотсос", "Ручной сбор"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Способ сбора образцов")
dev.off()
png("IMT.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "IMT") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Повышен", "Понижен", "Норма", "Сильно повышен"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "ИМТ")
dev.off()
png("L.Reuteri.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "L.Reuteri") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Прием пробиотиков")
dev.off()
png("Oksitocine.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Oksitocine") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Не было приема","Был прием"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Прием окситоцина во время беременности")
dev.off()
png("Anest.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Anest") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Эндотрахеальный наркоз", "Не было", "Спинальная анестезия"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Тип анестезии")
dev.off()
png("Epiziotom.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Epiziotom") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Была", "Не было"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Эпизиотомия")
dev.off()
png("Gender.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Gender") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Мальчик", "Девочка"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Пол ребенка")
dev.off()
png("Pregnancy_number.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Pregnancy_number") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Не первая", "Первая"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Беременность")
dev.off()
png("Age.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Age") + theme(aspect.ratio=1) +scale_color_manual(labels = c("25-29", "30-34","35-39", "больше 40","меньше 25"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Возраст роженицы")
dev.off()
png("Blood_type.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Blood_type") + theme(aspect.ratio=1) +scale_color_manual(labels = c("A", "AB","B","0"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Группа крови роженицы")
dev.off()
png("Fe_intake.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Fe_intake") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Прием препаратов железа")
dev.off()
png("Nationality.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Nationality") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Иностранки", "Русские"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Национальность")
dev.off()
png("Nikotin.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "Nikotin") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Не курит", "Курит"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Курение матери")
dev.off()

png("GSD.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(vst_physeq_new, ordination, color = "GSD") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Наблюдался", "Не наблюдался"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(fill = "Гестационный сахарных диабет")
dev.off()


######filter by column OLD - No###########
no_only<-row.names(dplyr::filter(sample_info_tab,Old== 'No'))
no_count_tab<-select(asvtab,all_of(no_only))
no_info_tab<-sample_info_tab[row.names(sample_info_tab) %in% no_only,]
no_phylo <- phyloseq(otu_table(no_count_tab, taxa_are_rows=T), sample_names(no_info_tab))
richness_no = estimate_richness(no_phylo, measures = c("Shannon", "Chao1", "Observed"))
write.table(richness_no, "alpha_no_richness.tsv", sep="\t", quote=F, col.names=NA)
richness_no$x <- rownames(richness_no)
richness_no$x<-gsub("X","",as.character(richness_no$x))
richness_no$x-> rownames(richness_no)
richness_no$x <- NULL
rownames(no_info_tab)<-as.character(rownames(no_info_tab))
comon_no <- merge(richness_no, no_info_tab, by=0)
row.names(comon_no)<-comon_no$Row.names
boxplot_chao_no<-ggplot(comon_no)
boxplot_chao_no+aes(x=Type_of_birthgiving, y= Chao1, color = Type_of_birthgiving)+geom_boxplot()+scale_color_manual(labels = c("Экстренное кесарево (ЭКС)", "Кесарево сечение (КС)", "Естественные роды (ЕР)"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+
  scale_x_discrete(labels=c("ЭКС", "КС", "ЕР"))+labs(x="Тип родоразрешения", color="Тип родоразрешения")+labs(fill = "Тип родоразрешения")+geom_jitter(cex=1, position=position_jitter(0.2))
boxplot_chao_no+aes(x=Ab_days_after_birth, y= Chao1, color = Ab_days_after_birth)+geom_boxplot()+scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+
  scale_x_discrete(labels=c("Был прием", "Не было приема"))+labs(x="Прием антибиотиков после родов", color="Прием антибиотиков\n после родов")+labs(fill = "Прием антибиотиков после родов")+geom_jitter(cex=1, position=position_jitter(0.2))
boxplot_chao_no+aes(x=nab, y= Chao1, color = nab)+geom_boxplot()+scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+
  scale_x_discrete(labels=c("Был прием", "Не было приема"))+labs(x="Прием антибиотиков во время беременности", color="Прием антибиотиков\n во время беременности")+labs(fill = "Прием антибиотиков во время беременности")+geom_jitter(cex=1, position=position_jitter(0.2))
boxplot_chao_no+aes(x=IMT, y= Chao1, color = IMT)+geom_boxplot()+scale_color_manual(labels = c("Повышен", "Понижен", "Норма", "Сильно повышен"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF", "#56B4E9"), )+theme_minimal()+
  scale_x_discrete(labels=c("Повышен", "Понижен", "Норма", "Сильно повышен"))+labs(x="ИМТ", color="ИМТ")+geom_jitter(cex=1, position=position_jitter(0.2))
boxplot_chao_no+aes(x=Oksitocine, y= Chao1, color = Oksitocine)+geom_boxplot()
#+scale_color_manual(labels = c("Повышен", "Понижен", "Норма", "Сильно повышен"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF", "#56B4E9"), )+theme_minimal()+
 


