library(ggplot2)
library(dada2)
library(DECIPHER)
library(readr)
library("DECIPHER")
library("Matrix")
library("ShortRead")
library("knitr")
library("BiocStyle")
library(readr)
library(phangorn)
library(DiagrammeR)
library(DiagrammeRsvg)
library(Rgraphviz)
library(phyloseq)
library(DESeq2)
library(dendextend)
library(vegan)
library(extrafont)
library(tidyr)
library(umap)
library("animalcules")
library(dplyr)
library(tidyverse)
library("ggpubr")
setwd("../final/")
asvtab <- read.table('ASVs_counts.tsv', header=TRUE, row.names=1, check.names=FALSE, sep="\t")
asv_tax<-read.table('ASVs_taxonomy.tsv',header=TRUE, row.names=1, check.names=FALSE, sep="\t",na.strings="NA")
sample_info_tab <- read.table("metadata_p.tsv",header=TRUE, row.names=1, check.names=FALSE, sep="\t")
asv_tax<- as.matrix(asv_tax)
vst_physeq <- phyloseq(otu_table(asvtab, taxa_are_rows=T), sample_names(sample_info_tab), tax_table(asv_tax))
richness = estimate_richness(vst_physeq, measures = c("Shannon", "Chao1", "Observed"))
richness$x <- rownames(richness)
richness$x<-gsub("X","",as.character(richness$x))
richness$x-> rownames(richness)
richness$x <- NULL
rownames(sample_info_tab)<-as.character(rownames(sample_info_tab))
comon <- merge(richness, sample_info_tab, by=0)
row.names(comon)<-comon$Row.names
results_kruskwal_sh <- list()
for(i in names(comon[,7:28])){  
  results_kruskwal_sh[[i]] <- kruskal.test(formula(paste("Shannon~",i)), data = comon)
}
results_kruskwal_sh_res <- capture.output(results_kruskwal_sh)
write.table(results_kruskwal_sh_res, "results_kruskwal_sh_res.txt")
results_kruskwal_ch <- list()
for(i in names(comon[,7:28])){  
  results_kruskwal_ch[[i]] <- kruskal.test(formula(paste("Chao1~",i)), data = comon)
}
results_kruskwal_ch_res <- capture.output(results_kruskwal_ch)
write.table(results_kruskwal_ch_res, "results_kruskwal_ch_res.txt")


res_chao_wil<- data.frame( x=rep(0, 14), y=rep(0,14))
for(i in names(comon[,c(8,9,12,14,15,16,20,21,22,24,25,26,27,28)])){
  res<-wilcox.test(formula(paste("Chao1~", i)), data = comon)
  res_chao_wil[i, ]<-c(paste(i), res$p.value)
}
vr<-filter(comon, comon[,7] =="VR") %>% pull(Chao1)
ks<-filter(comon, comon[,7] =="KS") %>% pull(Chao1)
eks<-filter(comon, comon[,7] =="EKS") %>% pull(Chao1)
m<-filter(comon, comon[,11] =="m") %>% pull(Chao1)
kh<-filter(comon, comon[,11] =="kh") %>% pull(Chao1)
f<-filter(comon, comon[,11] =="f") %>% pull(Chao1)
sma<-filter(comon, comon[,13] =="sma") %>% pull(Chao1)
etn<-filter(comon, comon[,13] =="etn") %>% pull(Chao1)
below25<-filter(comon, comon[,17] =="up to 25") %>% pull(Chao1)
below29<-filter(comon, comon[,17] =="25-29") %>% pull(Chao1)
below35<-filter(comon, comon[,17] =="30-34") %>% pull(Chao1)
below40 <-filter(comon, comon[,17] =="35-39") %>% pull(Chao1)
over40<-filter(comon, comon[,17] =="over 40") %>% pull(Chao1)
a<-filter(comon, comon[,18] =="A") %>% pull(Chao1)
b<-filter(comon, comon[,18] =="B") %>% pull(Chao1)
o<-filter(comon, comon[,18] =="O") %>% pull(Chao1)
ab<-filter(comon, comon[,18] =="AB") %>% pull(Chao1)
normal<-filter(comon, comon[,23] =="normal") %>% pull(Chao1)
high<-filter(comon, comon[,23] =="high") %>% pull(Chao1)
low<-filter(comon, comon[,23] =="low") %>% pull(Chao1)
obesity<-filter(comon, comon[,23] =="obesity") %>% pull(Chao1)

res_chao_wil<-rbind(res_chao_wil,c("vr vs ks",wilcox.test(vr,ks)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("vr vs eks",wilcox.test(vr,eks)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("ks vs eks",wilcox.test(eks,ks)$p.value))

res_chao_wil<-rbind(res_chao_wil,c("m vs kh",wilcox.test(m,kh)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("m vs f",wilcox.test(m,f)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("f vs kh",wilcox.test(f,kh)$p.value))

res_chao_wil<-rbind(res_chao_wil,c("sma vs etn",wilcox.test(sma, etn)$p.value))

res_chao_wil<-rbind(res_chao_wil,c("below25 vs below29",wilcox.test(below25, below29)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("below25 vs below35",wilcox.test(below25, below35)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("below25 vs below40",wilcox.test(below25, below40)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("below25 vs over40",wilcox.test(below25, over40)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("below29 vs below35",wilcox.test(below29, below35)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("below29 vs below40",wilcox.test(below29, below40)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("below29 vs over40",wilcox.test(below29, over40)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("below35 vs below40",wilcox.test(below35, below40)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("below35 vs over40",wilcox.test(below35, over40)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("below40 vs over40",wilcox.test(below40, over40)$p.value))

res_chao_wil<-rbind(res_chao_wil,c("a vs b",wilcox.test(a, b)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("a vs o",wilcox.test(a, o)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("a vs ab",wilcox.test(a, ab)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("b vs o",wilcox.test(b, o)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("b vs ab",wilcox.test(b, ab)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("o vs ab",wilcox.test(o, ab)$p.value))

res_chao_wil<-rbind(res_chao_wil,c("normal vs high",wilcox.test(normal, high)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("normal vs low",wilcox.test(normal, low)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("normal vs obesity",wilcox.test(normal,obesity)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("high vs low",wilcox.test(high, low)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("high vs obesity",wilcox.test(high, obesity)$p.value))
res_chao_wil<-rbind(res_chao_wil,c("low vs obesity",wilcox.test(low, obesity)$p.value))
res_chao_wil<-slice(res_chao_wil, 15:63)  

res_chao_wil$z<-p.adjust(res_chao_wil$y,method="fdr", n=length(res_chao_wil$y))
write.csv(res_chao_wil,"res_ch_wil.csv")

boxplot_chao<-ggplot(na.omit(comon))
png("Type_of_birthgiving_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Type_of_birthgiving, y= Chao1, color = Type_of_birthgiving)+geom_boxplot()+scale_color_manual(labels = c("Экстренное кесарево (ЭКС)", "Кесарево сечение (КС)", "Естественные роды (ЕР)"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("ЭКС", "КС", "ЕР"))+labs(x="Тип родоразрешения", color="Тип родоразрешения")+labs(fill = "Тип родоразрешения")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("nab_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=nab, y= Chao1, color = nab)+geom_boxplot()+scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Был прием", "Не было приема"))+labs(x="Прием антибиотиков во время беременности", color="Прием антибиотиков\n во время беременности")+labs(fill = "Прием антибиотиков во время беременности")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Ab_days_after_birth_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Ab_days_after_birth, y= Chao1, color = Ab_days_after_birth)+geom_boxplot()+scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Был прием", "Не было приема"))+labs(x="Прием антибиотиков после родов", color="Прием антибиотиков\n после родов")+labs(fill = "Прием антибиотиков после родов")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Stationary_time_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Stationary_time, y= Chao1, color = Stationary_time)+geom_boxplot()+scale_color_manual(labels = c("Длительное", "Короткое"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Длительное", "Короткое"))+labs(x="Время пребывания в стационаре", color="Время пребывания в стационаре")+labs(fill = "Время пребывания в стационаре")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Breast_treatment_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Breast_treatment, y= Chao1, color = Breast_treatment)+geom_boxplot()+scale_color_manual(labels = c("Фурацилин", "Хлоргексидин", "Мыло"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Фурацилин", "Хлоргексидин", "Мыло"))+labs(x="Способ обработки груди", color="Способ обработки груди")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Sampling_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Sampling, y= Chao1, color = Sampling)+geom_boxplot()+scale_color_manual(labels = c("Молокоотсос", "Ручной сбор"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Молокоотсос", "Ручной сбор"))+labs(x="Способ сбора образцов", color="Способ сбора образцов")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Old_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Old, y= Chao1, color = Old)+geom_boxplot()+scale_color_manual(labels = c("Молозиво", "Зрелое молоко"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Молозиво", "Зрелое молоко"))+labs(x="Степень зрелости молока", color="Степень зрелости молока")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("L.Reuteri_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=L.Reuteri, y= Chao1, color = L.Reuteri)+geom_boxplot()+scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Был прием", "Не было приема"))+labs(x="Прием пробиотиков", color="Прием пробиотиков")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("IMT_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=IMT, y= Chao1, color = IMT)+geom_boxplot()+scale_color_manual(labels = c("Повышен", "Понижен", "Норма", "Сильно повышен"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF", "#56B4E9"), )+theme_minimal()+scale_x_discrete(labels=c("Повышен", "Понижен", "Норма", "Сильно повышен"))+labs(x="ИМТ", color="ИМТ")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Oksitocine_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Oksitocine, y=Chao1, color=Oksitocine)+geom_boxplot()+scale_color_manual(labels = c("Не было приема","Был прием"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Не было приема","Был прием"))+labs(x="Прием окситоцина во время беременности", color="Прием окситоцина\n во время беременности")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Anest_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Anest, y= Chao1, color = Anest)+geom_boxplot()+scale_color_manual(labels = c("Эндотрахеальный наркоз", "Не было", "Спинальная анестезия"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Эндотрахеальный наркоз", "Без анестезии", "Спинальная анестезия"))+labs(x="Тип анестезии", color="Тип анестезии")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Epiziotom_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Epiziotom, y= Chao1, color = Epiziotom)+geom_boxplot()+scale_color_manual(labels = c("Была", "Не было"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Была", "Не было"))+labs(x="Эпизиотомия", color="Эпизиотомия")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Gender_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Gender, y= Chao1, color = Gender)+geom_boxplot()+scale_color_manual(labels = c("Мальчик", "Девочка"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Мальчик", "Девочка"))+labs(x="Пол ребенка", color="Пол ребенка")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Pregnancy_number_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Pregnancy_number, y= Chao1, color = Pregnancy_number)+geom_boxplot()+scale_color_manual(labels = c("Не первая", "Первая"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Не первая", "Первая"))+labs(x="Беременность", color="Беременность")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Age_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Age, y= Chao1, color = Age)+geom_boxplot()+scale_color_manual(labels = c("25-29", "30-34","35-39", "больше 40","меньше 25"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+scale_x_discrete(labels=c("25-29", "30-34","35-39", "больше 40","меньше 25"))+labs(x="Возраст роженицы", color="Возраст роженицы")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Blood_type_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Blood_type, y= Chao1, color = Blood_type)+geom_boxplot()+scale_color_manual(labels = c("A", "AB","B","0"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9"), )+theme_minimal()+scale_x_discrete(labels=c("A", "AB","B","0"))+labs(x="Группа крови роженицы", color="Группа крови роженицы")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Fe_intake_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Fe_intake, y= Chao1, color = Fe_intake)+geom_boxplot()+scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Был прием", "Не было приема"))+labs(x="Прием препаратов железа", color="Прием препаратов железа")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Nationality_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Nationality, y= Chao1, color = Nationality)+geom_boxplot()+scale_color_manual(labels = c("Иностранки", "Русские"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Иностранки", "Русские"))+labs(x="Национальность", color="Национальность")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("Nikotin_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=Nikotin, y= Chao1, color = Nikotin)+geom_boxplot()+scale_color_manual(labels = c("Не курит", "Курит"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Не курит", "Курит"))+labs(x="Курение матери", color="Курение матери")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()
png("GSD_chao.png",width = 5, height = 4, units = 'in', res = 300)
boxplot_chao+aes(x=GSD, y= Chao1, color = GSD)+geom_boxplot()+scale_color_manual(labels = c("Наблюдался", "Не наблюдался"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+scale_x_discrete(labels=c("Наблюдался", "Не наблюдался"))+labs(x="Гестационный сахарных диабет", color="Гестационный сахарных диабет")+geom_jitter(cex=1, position=position_jitter(0.2))
dev.off()

sample_info_tab_2 = sample_info_tab[rownames(t(asvtab)),]
sample_info_tab_2[is.na(sample_info_tab_2)]="NA_temporary"
sample_info_tab_2$Old =  as.factor(sample_info_tab_2$Old)
dist<-vegdist(t(asvtab),method="euclidean")
adonis<-adonis2(dist~L.Reuteri+IMT+Anest+Epiziotom+Gender+Pregnancy_number+Age+Blood_type+Fe_intake+Nationality+Nikotin+Oksitocine+GSD+Type_of_birthgiving+nab+Ab_days_after_birth+Stationary_time+Breast_treatment+Sampling+Old, data=sample_info_tab_2, permutations = 9999, by="margin")
adonis_res <- capture.output(adonis)
write.table(adonis_res, "adonis_res")

dist_bray<-vegdist(t(asvtab),method="bray")
adonis<-adonis2(dist_bray~L.Reuteri+IMT+Anest+Epiziotom+Gender+Pregnancy_number+Age+Blood_type+Fe_intake+Nationality+Nikotin+Oksitocine+GSD+Type_of_birthgiving+nab+Ab_days_after_birth+Stationary_time+Breast_treatment+Sampling+Old, data=sample_info_tab_2, permutations = 9999, by="margin")
adonis_res <- capture.output(adonis)
write.table(adonis_res, "adonis_res")
phylo_1 <- phyloseq(otu_table(asvtab, taxa_are_rows=T), sample_data(sample_info_tab), tax_table(asv_tax), treeNJ_rooted)

wunifrac_dist = phyloseq::distance(phylo_1, method="wunifrac")
ordination = ordinate(phylo_1, method="PCoA", distance=wunifrac_dist)
png("Type_of_birthgiving.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Type_of_birthgiving") + theme(aspect.ratio=1) +scale_color_manual(labels = c("Экстренное кесарево (ЭКС)", "Кесарево сечение (КС)", "Естественные роды (ЕР)"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+labs( col= "Тип родоразрешения")
dev.off()
png("nab.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "nab") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF"), )+theme_minimal()+labs(col = "Прием антибиотиков\n во время беременности")
dev.off()
png("Ab_days_after_birth.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Ab_days_after_birth") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Прием антибиотиков\n после родов")
dev.off()
png("Breast_treatment.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Breast_treatment") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Фурацилин", "Хлоргексидин", "Мыло"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Обработка груди")
dev.off()
png("Stationary_time.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Stationary_time") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Длительное", "Короткое"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Время пребывания\n в стационаре")
dev.off()
png("Old.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Old") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Молозиво", "Зрелое молоко"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Степень\ зрелости молока")
dev.off()
png("Sampling.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Sampling") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Молокоотсос", "Ручной сбор"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Способ\ сбора образцов")
dev.off()
png("IMT.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "IMT") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Повышен", "Понижен", "Норма", "Сильно повышен"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "ИМТ")
dev.off()
png("L.Reuteri.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "L.Reuteri") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Прием пробиотиков")
dev.off()
png("Oksitocine.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Oksitocine") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Не было приема","Был прием"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Прием окситоцина\n во время беременности")
dev.off()
png("Anest.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Anest") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Эндотрахеальный наркоз", "Не было", "Спинальная анестезия"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Тип анестезии")
dev.off()
png("Epiziotom.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Epiziotom") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Была", "Не было"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Эпизиотомия")
dev.off()
png("Gender.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Gender") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Мальчик", "Девочка"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Пол ребенка")
dev.off()
png("Pregnancy_number.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Pregnancy_number") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Не первая", "Первая"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Беременность")
dev.off()
png("Age.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Age") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("25-29", "30-34","35-39", "больше 40","меньше 25"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Возраст роженицы")
dev.off()
png("Blood_type.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Blood_type") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("A", "AB","B","0"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Группа\ крови роженицы")
dev.off()
png("Fe_intake.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Fe_intake") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Был прием", "Не было приема"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Прием\ препаратов железа")
dev.off()
png("Nationality.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Nationality") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Иностранки", "Русские"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Национальность")
dev.off()
png("Nikotin.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "Nikotin") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Не курит", "Курит"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Курение матери")
dev.off()
png("GSD.png",width = 5, height = 4, units = 'in', res = 300)
plot_ordination(phylo_1, ordination, color = "GSD") + theme(aspect.ratio=1,legend.position="bottom") +scale_color_manual(labels = c("Наблюдался", "Не наблюдался"),values = c("#ED7953FF", "#9C179EFF", "#0D0887FF","#56B4E9","#A52A2A"), )+theme_minimal()+labs(col = "Гестационный\ сахарных диабет")
dev.off()

getwd()


